// code generated by [generate-resource-dart-code] vscode-extension.
class AssetsImages {
  static const deletePng = 'assets/images/delete.png';
  static const eyePng = 'assets/images/eye.png';
  static const logoMylookPng = 'assets/images/logo_mylook.png';
  static const lukitaPng = 'assets/images/lukita.png';
  static const menuImagePng = 'assets/images/menu_image.png';
}

class AssetsSvgs {

}

